### PR TITLE
Revise and complete English translation of grammar

### PR DESCRIPTION
**Pull request by bluebear94**
Still working on this.

### CODE REVIEW

**Comment by Ziphil** [comment]
Thank you very much for your work!
Section 44 (Connectives) will be rewritten shortly according to the recent change of the usage of connectives, so please skip here until I rewrite that of the Japanese version.

**Comment by Ziphil** [comment]
I have rewritten Section 44 of the grammar; see [this commit](https://github.com/Ziphil/AvendiaNew/commit/7e99ca761d179ba2b0d5ebcc6f058b7f3d77dcd0).

**Comment by bluebear94** [comment]
I've finished the translation. Please review it.

**Comment by Ziphil** [comment]
Thank you so much! I will review this.

Is it okay to add a statement like "This grammar was translated by bluelear94" in the introduction section?

**Review by Ziphil — APPROVED** [review]

**Comment by Ziphil** [comment]
I squash-merged after correcting some syntax errors, but GitHub does not recognise it… (maybe I made a mistake in the process somewhere). So I close this PL manually.

After all, thank you very much for completing the translation!

**Pull request closed without merging**
